/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ProfileAvatar {
        /**
          * The Uri of the service - md5 hash of the email will be added to this uri
         */
        "avatarsUrl": string;
        /**
          * The avatar email - used to identify user icon
         */
        "email": string;
        /**
          * The size of the avatar in pixels
         */
        "size": string;
    }
    interface UfeAccountApp {
        "identity": string;
        "userName": string;
    }
}
declare global {
    interface HTMLProfileAvatarElement extends Components.ProfileAvatar, HTMLStencilElement {
    }
    var HTMLProfileAvatarElement: {
        prototype: HTMLProfileAvatarElement;
        new (): HTMLProfileAvatarElement;
    };
    interface HTMLUfeAccountAppElement extends Components.UfeAccountApp, HTMLStencilElement {
    }
    var HTMLUfeAccountAppElement: {
        prototype: HTMLUfeAccountAppElement;
        new (): HTMLUfeAccountAppElement;
    };
    interface HTMLElementTagNameMap {
        "profile-avatar": HTMLProfileAvatarElement;
        "ufe-account-app": HTMLUfeAccountAppElement;
    }
}
declare namespace LocalJSX {
    interface ProfileAvatar {
        /**
          * The Uri of the service - md5 hash of the email will be added to this uri
         */
        "avatarsUrl"?: string;
        /**
          * The avatar email - used to identify user icon
         */
        "email"?: string;
        /**
          * The size of the avatar in pixels
         */
        "size"?: string;
    }
    interface UfeAccountApp {
        "identity"?: string;
        "userName"?: string;
    }
    interface IntrinsicElements {
        "profile-avatar": ProfileAvatar;
        "ufe-account-app": UfeAccountApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "profile-avatar": LocalJSX.ProfileAvatar & JSXBase.HTMLAttributes<HTMLProfileAvatarElement>;
            "ufe-account-app": LocalJSX.UfeAccountApp & JSXBase.HTMLAttributes<HTMLUfeAccountAppElement>;
        }
    }
}
